id: A2C093723
title: Prayer for Swift Rebirth of Jamyang Khyentse Chökyi Lodrö
type: translation
pechas:
- IAC07C060
- I36974399
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:50:13.499230
  last_modified_at: 2023-01-04 11:50:13.499241
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IAC07C060/B3BC: '4992'
  I36974399/747B: '4992'
